remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme 

# Site settings
title: TLDR - Webpage Summarizer
description: Simplify Your Web Reading
theme: jekyll-theme-minimal

# Custom settings
tldr_intro: |
  TLDR - Webpage Summarizer offers instant summaries, saving you time and brainpower while browsing through webpages, research papers, news, blogs, and recipes. With TLDR, you can efficiently digest complex information and stay ahead of the curve.
testimonials:
  - quote: "TLDR - Webpage Summarizer has transformed the way I research and gather information online. It's fast, accurate, and incredibly convenient! With this tool, I can quickly digest complex articles and stay ahead of the curve."
    author: John Doe
    role: Journalist
  - quote: "As a student, TLDR - Webpage Summarizer has been a lifesaver during exam season. It helps me digest complex information quickly and efficiently, allowing me to focus on studying effectively. I highly recommend it to all my classmates!"
    author: Jane Smith
    role: Student
how_it_works: |
  TLDR - Webpage Summarizer employs advanced AI to analyze the structure and content of web pages. Here's how it works:
  1. Enter the URL of the webpage you want to summarize or paste the text directly into the tool.
  2. Our AI-powered system processes the content, extracting key information and eliminating unnecessary details.
  3. Within seconds, you'll receive a concise summary that captures the essence of the original content. It's that simple! Whether you're a student, researcher, journalist, or busy professional, TLDR - Webpage Summarizer revolutionizes the way you consume online content.
features_benefits:
  - title: "Instant Summaries"
    description: "Get quick summaries of lengthy content."
  - title: "Metadata Extraction"
    description: "Extract important information efficiently."
  - title: "Ad-Free Experience"
    description: "Enjoy distraction-free reading."
  - title: "Focus on Essence"
    description: "Get to the core of the content without the fluff."
  - title: "Customization Options"
    description: "Tailor summaries to your preferences."
  - title: "Share Summaries"
    description: "Easily share summarized content with others."
target_audience: |
  TLDR is perfect for:
  - Everybody
  - Students
  - Writers
  - Teachers
  - Institutions
  - Journalists
support_future_updates: |
  The TLDR - Webpage Summarizer extension is free for everyone to use. If you find it helpful and want to support its continued development and maintenance, consider subscribing. Your subscription helps us keep the updates coming and ensures the extension functions smoothly.
