const testConfig = {
    questions: [
        {
                "question": "A customer has been browsing in your section for about 10 minutes and is looking increasingly dissatisfied and frustrated. He approaches you and asks whether you have a particular book that he is looking for, and after checking on your computer, you have to inform him that it is currently 'out of stock'.\n\n",
                "options": [
                        "Apologise that the book is unavailable and suggest he try Morethanpens.co.uk or another online retailer instead.",
                        "Offer to order the book for the customer and let him know how long this will take. Offer to call him when the book arrives.",
                        "Give the customer the ISBN (book serial number) of the book so that he can easily and quickly search it out elsewhere, either online or at another bookshop.",
                        "Suggest he try the Alpston branch of More Than Pens (which is the nearest neighbouring town, 40 minutes drive away) or other bookshops in Saldringham."
                ],
                "correctAnswer": {
                        "most": 1,
                        "least": 0
                },
                "explanation": "Answer 2 is the most effective response as you are trying to give the customer what he wants without him having to do too much more. By telling the customer how long it will take to order, he can make an informed decision as to whether he wishes to take this option.\nAnswer 1 is the least effective response as you are not giving the customer any direct help and you are unaware as to whether the customer has access to a computer and is able to shop ‘online’.",
                "type": "most-least",
                "passage": "You are a Retail Assistant working in the Saldringham branch of More Than Pens plc, a national stationer's chain. More Than Pens has over 1000 stores, primarily in the UK, including 451 travel outlets at airports, train stations and motorway service areas and 627 high street stores. More Than Pens sells a wide range of newspapers, magazines, books, stationery and impulse products; most branches are open 7 days a week between 8.30am and 5.30pm. As a Retail Assistant you are responsible for providing exceptional customer service whilst demonstrating product knowledge to maximise sales. You work primarily in the book section of the Saldringham branch, however all the branch staff work as a unified team and therefore you are often required to work in other sections throughout the store."
        },
        {
                "question": "It is a Tuesday morning and a colleague in the stationery section is away on sick leave. At 11am you are on your way to the staff room to take a quick tea break when, passing through the stationery section, you notice that it is in a reasonable amount of disarray. Products have fallen on the floor and been left lying there, shelves are untidy and some products are on the wrong shelves.",
                "options": [
                        "Take your tea break and then on the way back quickly tidy up a few bits and pieces if it's still in a state.",
                        "Go back to your section and ask your team leader whether you can be spared for 10 or 15 minutes to help out in stationery. If agreed, offer your help to the stationery team leader to quickly tidy up the area and take your tea break at 11.30am.",
                        "Do nothing. The stationery team leader probably has it all under control and will deal with it soon. It's understandable that there's a bit of a mess as someone is away and you don't want to insult the stationery team by mentioning anything.",
                        "Inform the stationery team leader that there is a problem with the presentation of the section."
                ],
                "correctAnswer": {
                        "most": 1,
                        "least": 2
                },
                "explanation": "Answer 2 is  most effective response as you are quickly dealing with the problem whilst keeping everyone informed. You are not making artificial boundaries between the different sections in the store and ensuring that the store looks good as a whole rather than just worrying about your area\nAnswer 3 is the least effective response as you are making assumptions that the problem will be dealt with and the whole store will suffer if one section looks scruffy. It will give customers a poor impression of your More Than Pens branch.\n",
                "type": "most-least",
                "passage": "You are a Retail Assistant working in the Saldringham branch of More Than Pens plc, a national stationer’s chain. More Than Pens has over 1000 stores, primarily in the UK, including 451 travel outlets at airports, train stations and motorway service areas and 627 high street stores. More Than Pens sells a wide range of newspapers, magazines, books, stationery and impulse products; most branches are open 7 days a week between 8.30am and 5.30pm. As a Retail Assistant you are responsible for providing exceptional customer service whilst demonstrating product knowledge to maximise sales. You work primarily in the book section of the Saldringham branch, however all the branch staff work as a unified team and therefore you are often required to work in other sections throughout the store.\n\n"
        },
        {
                "question": "It is late June. You have just had your monthly ‘book section’ team meeting and your team leader has given you a special target for next month. You have been asked to work towards increasing sales of children's books by 15% compared to last July's figures. July is always a difficult month for children's products as it is the end of the summer term and families don't tend to spend money on books or stationery for children at this time. You will not have any extra budget available to achieve this goal.\n\n",
                "options": [
                        "Put a hand-written poster near the till promoting the great range of summer activity books that More Than Pens stock for children.",
                        "Pick out a selection of summer-themed books and ‘summer holiday activity books and put them near the front of the children's area.",
                        "Tidy up the children's book area and make it look as presentable as possible.",
                        "Approach as many customers with children (or who look like they may have children or grandchildren) and politely mention to them that More Than Pens has a great range of summer holiday activity books and story books for children and show them where the children's books are."
                ],
                "correctAnswer": {
                        "most": 3,
                        "least": 2
                },
                "explanation": "Answer 4 is the most effective response as you are actively promoting the summer-themed books and helping customers to find them. You may worry that this approach is slightly ‘pushy’ but without any budget for creating visual publicity this is the best and most dynamic way to raise customer awareness. You can also be on hand to offer help and advice if a customer shows an interest in buying books for the summer holidays.\n3 is the least effective response as there is no guarantee that this will do anything to attract extra customers to the area or encourage them to buy books when they are there. Of course, it should make sure that no customers are actively put off visiting the children’s area but this is the very minimum that you might wish to achieve.\n",
                "type": "most-least",
                "passage": "You are a Retail Assistant working in the Saldringham branch of More Than Pens pic, a national stationer's chain. More Than Pens has over 1000 stores, primarily in the UK, including 461 travel outlets at airports, train stations and motorway service areas and 627 high street stores. More Than Pens sells a wide range of newspapers, magazines, books, stationery and impulse products; most branches are open 7 days a week between 8.30am and 5.30pm. As a Retail Assistant you are responsible for providing exceptional customer service whilst demonstrating product knowledge to maximise sales. You work primarily in the book section of the Saldringham branch, however all the branch staff work as a unified team and therefore you are often required to work in other sections throughout the store."
        },
        {
                "question": "You are doing a stint on the till on a busy Saturday afternoon. You are working on the main bank of tills at the exit to the shop where customers from all parts of the shop can go to purchase their items. Suddenly the credit card transaction system stops working and one of the team leaders tells you that it will be 15 minutes until the system provider can fix the problem. There is a long queue of customers waiting.",
                "options": [
                        "Talk to the team leader and suggest that someone goes down the line of customers informing them of the problem and how long it will take to resolve. This will save customers queuing up in case they have no cash or chequebook on them.",
                        "Continue serving customers and apologise about the lack of availability of credit card payment.",
                        "Ask the team leader what to do.",
                        "Take the opportunity to take your afternoon tea break as it appears that most customers will have to come back later when the system is working again."
                ],
                "correctAnswer": {
                        "most": 0,
                        "least": 3
                },
                "explanation": "Answer 1 is the most effective response as there is nothing you can do to solve the IT problem yourself but you can give customers as much information as possible so that they can decide whether to continue queuing up or whether to come back later. Checking with the team leader is also appropriate as he or she may have a different plan and you don’t want to clash\n4 is the least effective response as you do not know for sure that most customers will have to pay later and you are leaving your colleagues and team leader to deal with the situation without checking what else you could do to help.",
                "type": "most-least",
                "passage": "You are a Retail Assistant working in the Saldringham branch of More Than Pens plc, a national stationer's chain. More Than Pens has over 1000 stores, primarily in the UK, including 451 travel outlets at airports, train stations and motorway service areas and 627 high street stores. More Than Pens sells a wide range of newspapers, magazines, books, stationery and impulse products; most branches are open 7 days a week between 8.30am and 5.30pm. As a Retail Assistant you are responsible for providing exceptional customer service whilst demonstrating product knowledge to maximise sales. You work primarily in the book section of the Saldringham branch, however all the branch staff work as a unified team and therefore you are often required to work in other sections throughout the store."
        },
        {
                "question": "Fiona Potter has delegated a project to you regarding the non-medical staff induction training course. The course has been run internally by Fiona and her colleague for the past few years but now her role has become busier and the HR Director has authorised the appointment of an external supplier to deliver the course and to refresh the content of the course. The project you are running has involved putting the course out to tender with various training suppliers and receiving bids back from the suppliers containing information on content of course, who would deliver it, length of course, expertise of the company, price to design and run the course and other relevant information. Fiona has given you the job of shortlisting the applicants; there are 20 companies who have bid and Fiona wants a shortlist of five to ask in to deliver a formal presentation. She has asked you to shortlist the bidding companies over the next two days.",
                "options": [
                        "Tell Mr Bowler that the process was fair and the hospital has to make sure that it appoints the right person for the job, not the one who has been around the longest.",
                        "Say to Mr Bowler that you can see why he is disappointed. State that the process was stringently fair and that he could seek full details of the reason for the decision and other developmental feedback from the interviewers if he would like to.",
                        "Say to Mr Bowler that you can see why he is disappointed. State that the process was stringently fair and that he could seek full details of the reason for the decision and other developmental feedback from the interviewers if he would like to.",
                        "Offer him a cup of tea and say that you can understand why he is upset. Let him have a bit of a moan to you and get it out of his system."
                ],
                "correctAnswer": {
                        "most": 2,
                        "least": 1
                },
                "explanation": "3 is  the most effective response. You are empathising with Mr Bowler but not supporting his negative view of the process. You are encouraging him to seek more information and feedback as to why he didn’t get the job which may help him develop and continue to contribute well to the department and the hospital.\n2 is the least effective response. Since you are only an assistant it is not your role to give such feedback to Mr Bowler, which may be counterproductive. You should be encouraging him to seek feedback from the interviewers directly. Also, Mr Bowler needs to be given a fully-rounded picture of his performance at the interview and why the interviewers felt that they wouldn’t offer him the job on this occasion.",
                "type": "most-least",
                "passage": "You are a Human Resources (HR) Assistant working in the HR Department of a busy NHS Hospital Trust. The hospital is the Princess Aurora General in Saldringham City. Your role is to carry out administrative tasks to support the HR activities required in the Trust. You organise and support recruitment, book training courses, provide secretarial support at disciplinary investigations and keep personnel records for all medical and non-medical staff up-to-date including pay and conditions information.You report to one of two HR Managers who in turn report to the HR Director. Your manager is called Fiona Potter."
        },
        {
                "question": "Fiona Potter has delegated a project to you regarding the non-medical staff induction training course. The course has been run internally by Fiona and her colleague for the past few years but now her role has become busier and the HR Director has authorised the appointment of an external supplier to deliver the course and to refresh the content of the course. The project you are running has involved putting the course out to tender with various training suppliers and receiving bids back from the suppliers containing information on content of course, who would deliver it, length of course, expertise of the company, price to design and run the course and other relevant information. Fiona has given you the job of shortlisting the applicants; there are 20 companies who have bid and Fiona wants a shortlist of five to ask in to deliver a formal presentation. She has asked you to shortlist the bidding companies over the next two days.",
                "options": [
                        "Place all 20 suppliers on a grid and allocate points on a 1 to 5 scale according to each factor about which you have information (e.g. a company might score '1' on price but '5' on experience-level of their trainers).",
                        "Order the companies in terms of their prices and shortlist the five lowest-priced bids since the NHS should always be cost-conscious.",
                        "Ask Fiona and the HR Director for their views on what the key criteria should be for shortlisting the bidders and use this information to structure your decision-making.",
                        "Email a contact in at the Alpston University Hospital Trust who has done this type of thing before and ask for input on how to shortlist the bidders."
                ],
                "correctAnswer": {
                        "most": 2,
                        "least": 1
                },
                "explanation": "3 is most effective response. Fiona has run the course for years and will have a good handle on what the requirements are. The HR Director may have some ideas about how the course should be designed and delivered in the future. You can combine the two viewpoints to create an informed and well-structured shortlisting process.\n2 is least effective response. Price is, of course, important but quality and other considerations cannot be disregarded otherwise the end product and delivery of the course could be disastrous.",
                "type": "most-least",
                "passage": "You are a Human Resources (HR) Assistant working in the HR Department of a busy NHS Hospital Trust. The hospital is the Princess Aurora General in Saldringham City. Your role is to carry out administrative tasks to support the HR activities required in the Trust. You organise and support recruitment, book training courses, provide secretarial support at disciplinary investigations and keep personnel records for all medical and non-medical staff up-to-date including pay and conditions information.You report to one of two HR Managers who in turn report to the HR Director. Your manager is called Fiona Potter."
        },
        {
                "question": "The Princess Aurora has recently been suffering from a high turnover of nursing assistants with many leaving to work at the privately-run Sunnyside Hospital & Rehabilitation Clinic on the outskirts of the city. In exit interviews, leavers have stated that by leaving they are hoping to increase their pay. Some of the leavers also mentioned that the attractions of the private hospital are its scenic location and its great range of staff facilities, including use of an indoor swimming pool. You have been asked to design and run a recruitment campaign to attract and appoint 10 new nursing assistants and trainee nursing assistants to the Trust. One of your measures of success will be the 'staying power' of the new recruits. You have 4 weeks from now until the date that the interviews for the nursing assistant candidates will run.",
                "options": [
                        "Place an advertisement immediately in all the relevant local media and online. Then spend some time designing a shortlisting process which will identify candidates with the sort of values that will translate into loyalty to the NHS.",
                        "Ask your colleague in the HR team what the process was last time the Trust recruited nursing assistants and follow that plan.",
                        "Work back from the date of the interviews to establish when you might need to advertise the posts. Use the intervening time to use your judgement in drafting an advert to try and attract people whose values mean they are more likely to remain loyal to the NHS.",
                        "Ask local recruitment advertising agencies for advice on drafting an advert to attract the kind of people who are less likely to leave."
                ],
                "correctAnswer": {
                        "most": 2,
                        "least": 1
                },
                "explanation": "3 is most effective response. You are keeping the final deadline and deliverables in mind but also attending to some things that might help you hit your key success measure of ‘retention’.\n2 is least effective response. The previous process failed to attract and appoint candidates who had loyalty to the Trust and the NHS; a change is required. However, the outline of the plan could be salvaged, if just in terms of the timescales to do things.",
                "type": "most-least",
                "passage": "You are a Human Resources (HR) Assistant working in the HR Department of a busy NHS Hospital Trust. The hospital is the Princess Aurora General in Saldringham City. Your role is to carry out administrative tasks to support the HR activities required in the Trust. You organise and support recruitment, book training courses, provide secretarial support at disciplinary investigations and keep personnel records for all medical and non-medical staff up-to-date including pay and conditions information.You report to one of two HR Managers who in turn report to the HR Director. Your manager is called Fiona Potter."
        },
        {
                "question": "The new induction training course is up and running and has been very well received by attendees and departmental managers alike. You have scheduled all the courses for the 12 months ahead and the company providing the training has little spare capacity to deliver any extra courses. The Trust has recently appointed 8 new nursing assistants who are all due to start over the next month or so. First thing this morning, you received a call from the Head of Nursing, Sally O'Hara requesting that all the eight new nursing assistant starters be induction trained within two weeks of beginning their employment. Your problem is that all the induction courses for the next 3 months are fully booked. You explained this to Sally, but she was adamant that these nursing assistants need to be given an immediate, good quality induction to the Trust to build their loyalty to the organisation and hopefully reduce turnover amongst that group.\n\nYou said to Sally that you would have to look at the situation in more detail and that you would call her back later this morning. Since then, having spoken to Fiona, the decision is that the nursing assistants require no special treatment and that you will book all 8 of them on the next available courses in 4 month's time. Now you need to convey this to Sally.",
                "options": [
                        "Apologise to Sally for the fact that you can't fit her staff onto the course over the next three months. Offer to monitor the courses and notify her immediately if there are any cancellations and say that her staff will be top of the list for any spaces that become available.",
                        "Tell Sally that her staff are no more important than any others at the Trust and that they will have to be slotted into the courses when there are spaces in a few months time.",
                        "Apologise to Sally and say that you have allocated places to her new starters on the first available courses, explain that you have reviewed all the attendees on the course over the next three months and you are unable to reschedule any of them.",
                        "Apologise to Sally and explain that there are no places available. Suggest that she do some one-to-one induction sessions with the new starters herself."
                ],
                "correctAnswer": {
                        "most": 0,
                        "least": 1
                },
                "explanation": "1 is most effective response. You are really demonstrating that you care about Sally and her employees and that you are doing all you can to get her the training she wants for her staff.\n2 is least effective response. You risk alienating a senior member of staff.",
                "type": "most-least",
                "passage": "You are a Human Resources (HR) Assistant working in the HR Department of a busy NHS Hospital Trust. The hospital is the Princess Aurora General in Saldringham City. Your role is to carry out administrative tasks to support the HR activities required in the Trust. You organise and support recruitment, book training courses, provide secretarial support at disciplinary investigations and keep personnel records for all medical and non-medical staff up-to-date including pay and conditions information.You report to one of two HR Managers who in turn report to the HR Director. Your manager is called Fiona Potter."
        },
        {
                "question": "One of the first projects allocated to you upon joining the HR department is to run a review of recruitment services purchased by Sutton & Sykes. You have been asked to allocate a new 12 month contract to the supplier(s) who you believe will provide the best 'value for money'. Today you are attending a brief meeting with other members of the review team to make a decision based on your findings. You will be meeting with a colleague from finance, a senior manager from the research division and the HR business partner for manufacturing & assembly.\n\nFrom your analysis of the range of suppliers available in the recruitment market you have arrived at a shortlist of three large recruitment consultancies. You believe that these are the only ones who have the expertise and understanding required to recruit the specialist engineering and research staff required. You know that your finance colleague favours supplier A as they are the least expensive, the senior manager favours supplier B as he has a good relationship with their lead consultant and the HR business partner favours supplier C as they are considered to be the 'gold standard' in the industry in terms of best practice. You need to come to a conclusion by the end of this one hour meeting.",
                "options": [
                        "Open the meeting by asking for your colleagues views and then allow a free-flowing debate in which a natural consensus should arise by the end of the meeting.",
                        "Allow a free-flowing debate for the first 15 minutes and then gradually suggest some structure (for example: agreeing criteria, systematically analysing the options against these criteria) in order to reach a decision in a timely manner.",
                        "At the outset, suggest that you use set criteria to analyse the three options, that the group agrees these criteria to begin with and that you divide the hour into three sections - agreement of criteria, discussion of options against criteria and final decision.",
                        "Set out your opinion quite clearly and confidently at the beginning of the meeting, listing pros and cons for each option and then stating which consultancy you feel is the best for Sutton & Sykes. Then ask your colleagues for their opinions."
                ],
                "correctAnswer": {
                        "most": 1,
                        "least": 0
                },
                "explanation": "2 is best response.  This is the most effective response as you are allowing your colleagues the time to express themselves as they might expect given their seniority and you are then supporting and helping the group to reach a decision and overcome any disagreement.\n1  is the least effective response as there is no guarantee that your colleagues will be able to build a consensus and there is a danger of the meeting ending with no decision being made.",
                "type": "most-least",
                "passage": "You are working as a Graduate Trainee for Sutton & Sykes, a manufacturer of domestic electrical goods for the UK and European market. You are on a rotational placement programme spending 6 months in each of 4 different departments of the company in order to 'learn the ropes' before being assessed for a permanent management position. You have completed your placements in Manufacturing and in Facilities Services. You are half-way through your 6 months in the Human Resources (HR) department. The HR team are based in Alton, Hampshire at Sutton & Sykes HQ. The other company sites are located around the SE of England, including a large manufacturing and assembly plant on the Isle of Wight and a research division in Southampton. Your final placement will be with the Finance department and is due to commence upon completion of your 6 months in HR."
        },
        {
                "question": "You have had an email from a senior manager in the Finance department, Sally Arkwright, who will be your placement supervisor when you join the team in 3 months' time. She is keen that you are aware that you will be joining the department at their busiest time. You are due to start in Finance in January which is the peak financial planning season. The staff will be working flat out to produce the annual business plans and budget allocations for each department in Sutton & Sykes and to align this with the projections of profit & loss for the business. Your supervisor feels that it is very important you are aware of this so you can 'hit the ground running' when you join the team. You have never worked in a finance role before.",
                "options": [
                        "Search on the internet for information about business planning, budgeting and profit & loss calculation.",
                        "Email Sally and ask whether it would be possible to have a one-to-one meeting with her before you begin your placement to find out as much as possible about the projects on which you might be working.",
                        "Thank Sally and say that you will contact her in December, a few weeks before your placement, and ask for specific details of your projects.",
                        "Email Sally thanking her for her early warning. Ask her whether she can provide any information on the projects on which you might be working in January."
                ],
                "correctAnswer": {
                        "most": 1,
                        "least": 2
                },
                "explanation": "2 is the most effective response as you will be able to find out the maximum amount of detail from Sally before you start the placement. By doing this you will be able to undertake tailored and focused learning to enhance your skills and knowledge before you start\n3  is the least effective response as, although if you took the other approaches suggested it may turn out that you would have to wait until this time for the specific details of projects, at least with those responses you could be doing work to prepare much earlier than a few weeks before the start of your placement.",
                "type": "most-least",
                "passage": "You are working as a Graduate Trainee for Sutton & Sykes, a manufacturer of domestic electrical goods for the UK and European market. You are on a rotational placement programme spending 6 months in each of 4 different departments of the company in order to 'learn the ropes' before being assessed for a permanent management position. You have completed your placements in Manufacturing and in Facilities Services. You are half-way through your 6 months in the Human Resources (HR) department. The HR team are based in Alton, Hampshire at Sutton & Sykes HQ. The other company sites are located around the SE of England, including a large manufacturing and assembly plant on the Isle of Wight and a research division in Southampton. Your final placement will be with the Finance department and is due to commence upon completion of your 6 months in HR."
        },
        {
                "question": "It is 9am on a Monday morning and you have just received an email from your boss, Maria Alvarez, asking that you bring forward the deadline to 'close of play' today for a small research project that you were doing for her. She says that she requires the written report from you a day early (when she told you about the report on Friday she said that it would be due by the end of tomorrow) as she has an urgent meeting about the matter tomorrow morning. You haven't started work on the report yet and you estimate it will take you 4 or 5 hours to complete.\n\nThere are two other emails in your inbox. One is from an HR colleague who is off sick today but was due to attend an HR liaison meeting in Southampton with the Head of the Research Department. The email says that he has asked Maria and she is happy for you to go in his place. The meeting is due to start at 11am and the drive from Alton to Southampton takes approximately 1 hour.\n\nThe third email is a reminder about a feedback sheet that the Graduate Development Manager (GDM) sent out to all Graduate Trainees a week ago. He is seeking your feedback and views on how to improve the trainee programme for the new intake in January. You have glanced at the sheet and it is a four-page questionnaire which requires some thoughtful input from you. The GDM wants the form returned by the end of the day to give him time to analyse the feedback and put it to good use.",
                "options": [
                        "Speak to Maria and explain that if you go to the meeting in Southampton it may stop you getting your report done on time and therefore it would be better if someone else went instead. Email the GDM and say that unfortunately you might not get the feedback to him until tomorrow mid-morning.",
                        "Say that you will attend the meeting and then return to the office this afternoon to complete your report for Maria. Email the GDM and say that you may not get the feedback to him until tomorrow mid-morning.",
                        "Complete the feedback sheet for the GDM first thing as this has been waiting for the longest time to be done. Say to Maria that you can't attend the meeting because if you do you might not complete her report. Spend the remainder of the day writing your report for Maria.",
                        "Agree to attend the meeting and flag up to Maria that you are going. Email the GDM and apologise that you won't be able to get him the feedback until mid-morning tomorrow. Email the Head of the Research Department and apologise that you will only be able to meet for up to 1 hour today due to a busy schedule; ask if he would rather re-schedule when your colleague is back at work or if he is happy with a short meeting. Start your report between 9am and 10am. Attend the meeting, if appropriate, and then return to Alton by 1pm and write your report for Maria until 5pm."
                ],
                "correctAnswer": {
                        "most": 3,
                        "least": 2
                },
                "explanation": "4 is the most effective response as, by limiting the length of the meeting there is sufficient time in the day to complete the two urgent and important tasks. The GDM feedback report is important but not time-critical as the new trainee intake don’t arrive for another 3 months\n3 is the least effective response as the feedback to the GDM is the least time critical task. Although it is of high importance, even if you get the feedback to him a few hours late he should still be able to use it, as analysing all the feedback sheets will take him a reasonable amount of time anyway.",
                "type": "most-least",
                "passage": "You are working as a Graduate Trainee for Sutton & Sykes, a manufacturer of domestic electrical goods for the UK and European market. You are on a rotational placement programme spending 6 months in each of 4 different departments of the company in order to 'learn the ropes' before being assessed for a permanent management position. You have completed your placements in Manufacturing and in Facilities Services. You are half-way through your 6 months in the Human Resources (HR) department. The HR team are based in Alton, Hampshire at Sutton & Sykes HQ. The other company sites are located around the SE of England, including a large manufacturing and assembly plant on the Isle of Wight and a research division in Southampton. Your final placement will be with the Finance department and is due to commence upon completion of your 6 months in HR."
        },
        {
                "question": "You are taking part in a meeting with your boss Maria. You have been asked to participate in the meeting with the representatives of a potential new retail customer, Jack Lanis Stores. Jack Lanis Stores (JLS) is a substantial group of department stores which has built a strong brand as an ethical and responsible retailer. The chain prides itself on bringing British-made, eco-friendly and responsibly-sourced products to market in the UK high street. As Jack Lanis is run as a co-operative, where all its employees own a part of the company, they look at potential suppliers' records with regard to the ethical and fair treatment of employees. This includes levels of pay and employees' contracted terms and conditions. If this meeting goes well (i.e. the Jack Lanis representatives emerge confident that Sutton & Sykes are a fair and ethical company with regard to the way it treats its employees) then a large deal could be signed for Sutton & Sykes to supply 40,000 washing machines and 14,000 tumble dryers per year to the retail chain. Half-way through the meeting, Nazib Khan, the senior buyer from JLS, turns to you, as a relative newcomer to the company, and asks what your views are on Sutton & Sykes.",
                "options": [
                        "Thank Mr Khan for asking your opinion and check what it is that he would like to hear about in particular, then try to respond to his interest as honestly and positively as possible.",
                        "Thank Mr Khan for asking your opinion and say that you have always been treated in accordance with Sutton & Sykes' fair and ethical employment structure. Illustrate this by showing Mr Khan a Sutton & Sykes' employment policy document.",
                        "Give an honest and positive account of your recruitment, selection, training and management as a graduate trainee; include a few specific examples of how these things were done fairly and ethically by Sutton & Sykes.",
                        "Thank Mr Khan for asking your opinion but say that the meeting was supposed to be about Sutton & Sykes' policies and procedures for all employees and your experience might not be a representative one, therefore you'd rather not go into too much detail about yourself."
                ],
                "correctAnswer": {
                        "most": 0,
                        "least": 3
                },
                "explanation": "1 is the most effective response as, you are trying to find out what Mr Khan would like to know before answering his question, in this way you will be able to tailor your account to give him information on the things in which he is interested\n4 is the least effective response as you are failing to respond at all to Mr Khan’s interest in getting a ‘personal’ perspective on the issue.\n",
                "type": "most-least",
                "passage": "You are working as a Graduate Trainee for Sutton & Sykes, a manufacturer of domestic electrical goods for the UK and European market. You are on a rotational placement programme spending 6 months in each of 4 different departments of the company in order to 'learn the ropes' before being assessed for a permanent management position. You have completed your placements in Manufacturing and in Facilities Services. You are half-way through your 6 months in the Human Resources (HR) department. The HR team are based in Alton, Hampshire at Sutton & Sykes HQ. The other company sites are located around the SE of England, including a large manufacturing and assembly plant on the Isle of Wight and a research division in Southampton. Your final placement will be with the Finance department and is due to commence upon completion of your 6 months in HR."
        },
        {
                "question": "A customer approached you on the shop floor. He appeared flustered and angry. He wanted to return an electric hand mixer that he purchased 3 months ago from this store. He said that he has only used the mixer twice and on the second occasion the whisk attachment broke off in the pudding mixture he was preparing and he couldn't attach it back onto the mixer handle. The customer has no receipt for the purchase. Jack Lanis normal returns policy is 'no quibble' 28 day refund or exchange for all purchases. After this time customers need to show a receipt as 'proof of purchase'. When you informed the customer of this he started shouting at you saying that he couldn't believe that he was being treated in such a manner and that he had clearly been sold faulty goods.",
                "options": [
                        "Say that you can understand the customer's frustration, apologise and ask him to come with you to the Customer Service desk where you can consult the supervisor on duty with regard to how the rules apply in this case. Say that you will do your very best to ensure he goes away satisfied today, either with a replacement item or with a guarantee to have it repaired.",
                        "Apologise and say that there is nothing you can do as he doesn't have a receipt. Explain that the policy is there because customers could buy items in another shop or even shoplift them and then try to get their money back.",
                        "Say that he may have been using the mixer for the wrong type of cooking. Perhaps the mixture for his pudding was too thick? Ask whether he had read the instructions properly before using the mixer.",
                        "Ask the customer to show you the mixer and see if there is anything you can do to repair it.",
                        "Apologise to the customer and suggest that a credit card statement with the purchase on it might suffice as 'proof of purchase'. You will check with your supervisor."
                ],
                "correctAnswer": {
                        "most": 0,
                        "least": 2
                },
                "explanation": "1 is best response. You have acknowledged the customer’s frustration, said sorry and you are showing him that you are going to pursue the matter and try to resolve it.\n3 is worst response. Blaming the customer for a faulty or broken product is counterproductive as, although there is a chance it may be true, you are unlikely to be able to prove he had misused the item and you will anger him further.",
                "type": "most-least",
                "passage": "You are a retail assistant in the kitchenware department of the Jack Lanis Stores branch in Leamouth-on-Sea. Jack Lanis Stores (JLS) is a large chain of department stores which has built a strong brand as an ethical and responsible retailer. The chain prides itself on bringing British-made, eco-friendly and responsibly-sourced products to market in the UK high street.\n\nYour role is:\nTo meet and greet customers\nTo give customers detailed information and advice about products\nTo maintain stock levels by re-filling from the stock room as necessary or flagging up larger items that need re-ordering from the warehouse or the manufacturer\nTo keep the shop floor presentable and tidyTo operate the electronic till for cash, credit card and store card sale transactions, refunds and exchanges."
        },
        {
                "question": "It is 10am. A customer has been in the department for the past 45 minutes looking at dishwashers and asking you for advice and information on makes and models. She has three children and her husband works from home so she needs a machine that will be robust and can endure a lot of use. She has a budget of £300. You have shown her the two most suitable machines. One is a cheaper model costing £299 which is fine but will probably last only 2 or 3 years with the high level of use she is describing. There is also a model which is of far superior quality which came on the market at an introductory offer price of £350 two weeks ago; the offer ends today and the model will revert to its normal price of £499 when the shop closes today. You believe that this model will last her and her family between 5 and 8 years of use. The customer is unsure about the extra £50 over her budget allocation and says she feels uncomfortable buying at the higher price without consulting her husband.",
                "options": [
                        "Say that you can understand her worries and perhaps she should give her husband a call to discuss it with him. Remind her of the savings on the 'offer' machine, in that its longevity will be twice that of the cheaper model. So, in other words, she could spend nearly £600 for 6 years' use with the other model (as she'll have to replace it after 3 years) or £350 for 6 years' use with the superior model.",
                        "Say that you are very worried she will miss out on this deal if she doesn't make a decision soon.",
                        "Leave the customer to ponder her decision.",
                        "Say that it is often better to buy a quality item than a 'cheap and cheerful' one.",
                        "Remind the customer of the 'real' savings she would make if she purchased the more expensive but better quality machine. Over 6 years she would be paying £350 instead of £600 for two cheaper machines."
                ],
                "correctAnswer": {
                        "most": 0,
                        "least": 1
                },
                "explanation": "1 is best response. You are giving the customer accurate guidance and a realistic solution of calling her husband to include him in the decision-making, but you’re not being so ‘pushy’ as to put her off.\n2 is worst response because counterproductive. You are pressurising the customer and this may put her off buying from your store altogether.",
                "type": "most-least",
                "passage": "You are a retail assistant in the kitchenware department of the Jack Lanis Stores branch in Leamouth-on-Sea. Jack Lanis Stores (JLS) is a large chain of department stores which has built a strong brand as an ethical and responsible retailer. The chain prides itself on bringing British-made, eco-friendly and responsibly-sourced products to market in the UK high street.\n\nYour role is:\nTo meet and greet customers\nTo give customers detailed information and advice about products\nTo maintain stock levels by re-filling from the stock room as necessary or flagging up larger items that need re-ordering from the warehouse or the manufacturer\nTo keep the shop floor presentable and tidyTo operate the electronic till for cash, credit card and store card sale transactions, refunds and exchanges."
        },
        {
                "question": "You have arrived for work at 8.30am on a Monday. You are working an eight hour shift finishing at 4.30pm. The shop is open from 9am to 6pm today. There are only two of you on duty today as a colleague has called in sick.\n\nYou now find that there are the following tasks for the Kitchen department written in the diary by your supervisor, who is due in at 9.30am:\n\n- Sort a delivery of utensils and silverware that came in late on Saturday, ensure it is properly shelved in the stock room.- Check the department and stock up the shelves and displays where necessary, Saturday was very busy and no-one had a chance to do this.- Dismantle a special offer display for Sutton & Sykes Dishwashers as the offer expired on Saturday at 5.30pm.- Clean and tidy the till area as it has been left in a bit of a state by the Saturday team.- One of you should attend the inter-departmental staff meeting from 10am to 11am today.",
                "options": [
                        "Quickly talk through the tasks with your colleague. Suggest you deal with the delivery first as the store isn't open yet and you can both work on it until 9am. Identify the 'special offer' display and tidying the till as the next most important tasks. See if you can get a summary of the meeting from a colleague in another department so neither of you need attend.",
                        "Start work on the special offer display immediately, you are concerned about the legal implications. Say to your colleague that you will talk through the rest of the tasks with her later.",
                        "Wait to talk to your supervisor and ask her opinion on the priority of the tasks and whether to attend the meeting as you have an absent colleague.",
                        "Dismantle the special offer display immediately as you are concerned that customers will be misled. Then tidy the till area and prepare for customers. Decide on who will attend the meeting and the other one remain in the department to re-merchandise and to deal with customers. Once the meeting is finished there should be time in the remainder of the day to deal with the delivery.",
                        "Deal with the delivery first as the shop isn't open and you can both work on it until 9am. Dismantle the special offer display straightaway at 9am whilst your colleague tidy's the till area. Decide on who will attend the meeting and the other one remain in the department to re-merchandise and to deal with customers."
                ],
                "correctAnswer": {
                        "most": 0,
                        "least": 2
                },
                "explanation": "1 is best response. The tasks are correctly prioritised and you may gain an extra person hour by avoiding the meeting but you rightly make sure you hear what was said at the meeting.\n3 is worst and counterproductive response. You are wasting an hour of you and your colleague’s time.",
                "type": "most-least",
                "passage": "You are a retail assistant in the kitchenware department of the Jack Lanis Stores branch in Leamouth-on-Sea. Jack Lanis Stores (JLS) is a large chain of department stores which has built a strong brand as an ethical and responsible retailer. The chain prides itself on bringing British-made, eco-friendly and responsibly-sourced products to market in the UK high street.\n\nYour role is:\nTo meet and greet customers\nTo give customers detailed information and advice about products\nTo maintain stock levels by re-filling from the stock room as necessary or flagging up larger items that need re-ordering from the warehouse or the manufacturer\nTo keep the shop floor presentable and tidyTo operate the electronic till for cash, credit card and store card sale transactions, refunds and exchanges."
        },
        {
                "question": "A customer is in the store looking at the coffee makers available in your department. He has asked your advice on which coffee maker to buy.Coffee makers vary on a number of criteria:\n\n- The form of coffee that they use (e.g. coffee beans, ground coffee, espresso coffee, coffee capsules).- Branded vs JLS own-brand machines (own-brand tend to be less expensive for similar specification machines).- Whether they are standalone (need to be placed on counter-top) or integrated (can be installed as part of a fitted kitchen).- Price (which in your branch of JLS varies from £140 to £1150). Price can indicate a desirable brand, styling and level of automation in a product.",
                "options": [
                        "Check how much time the customer has available. Have a detailed conversation with the customer and find out about what they will use the machine for (e.g. daily use or dinner parties etc), what their kitchen is like, what is their attitude to styling and to price and what type of coffee they prefer to drink.",
                        "Check how much time the customer has available. Have a detailed conversation with the customer and find out about what they will use the machine for (e.g. daily use or dinner parties etc), what their kitchen is like, what is their attitude to styling and to price and what type of coffee they prefer to drink.",
                        "Say to the customer that all the products in JLS are guaranteed and of high quality and that this type of decision is a very subjective. Therefore you think it best that he make his mind up himself without interference from you.",
                        "Ask him what type of coffee he likes and point him in the direction of the appropriate coffee machines that JLS stocks.",
                        "Say that you would be really interested to find out some information in order to help him make the decision. You specifically want to know about what he will use the machine for (e.g. daily use or dinner parties etc), what his kitchen is like, what is his attitude to styling and to price and what type of coffee he prefers to drink."
                ],
                "correctAnswer": {
                        "most": 0,
                        "least": 2
                },
                "explanation": "1 is best response. If the customer has some time available then going through this process of examining his requirements and tastes, as well as his budget, will help him to come to a sound and satisfying decision about this purchase.\n3 is worst and counterproductive response. You are not providing the required service to the customer or fulfilling your job description.",
                "type": "most-least",
                "passage": "You are a retail assistant in the kitchenware department of the Jack Lanis Stores branch in Leamouth-on-Sea. Jack Lanis Stores (JLS) is a large chain of department stores which has built a strong brand as an ethical and responsible retailer. The chain prides itself on bringing British-made, eco-friendly and responsibly-sourced products to market in the UK high street.\n\nYour role is:\nTo meet and greet customers\nTo give customers detailed information and advice about products\nTo maintain stock levels by re-filling from the stock room as necessary or flagging up larger items that need re-ordering from the warehouse or the manufacturer\nTo keep the shop floor presentable and tidyTo operate the electronic till for cash, credit card and store card sale transactions, refunds and exchanges."
        }
],
    timeLimit: 1200 // 20 minutes in seconds
};

// Initialize the test
const testCore = new TestCore(testConfig);
testCore.start();