const testConfig = {
    questions: [
        {
                "question": "It is 7.30pm. You are on duty at the concierge desk when a guest calls down to say that they have just checked in and are extremely unhappy with the cleanliness of their room. They say that the sink has hair in it, the tea cups are smeared and the curtains are dusty. The guest is only at the Grand for one night and has a business meeting in Alpston first thing in the morning. \nReview the following responses A to D and indicate which one you believe to be the response to the situation you would be ‘most likely to make’ and the response to the situation which you would be ‘least likely to make’. \n",
                "options": [
                        "Apologise to the customer and say that you will ensure that the room is cleaned thoroughly within the next hour. ",
                        "Apologise and offer the customer a different room immediately; if necessary an upgraded room if no others are available in his original price range. ",
                        "Apologise and offer the customer a discount on his room rate. ",
                        "Apologise and arrange a complimentary room service meal and bottle of wine to be  sent to the room. "
                ],
                "correctAnswer": {
                        "most": 1,
                        "least": 3
                },
                "explanation": "2 is the most effective response as the customer will not have to wait for the situation to be rectified and he should be immediately satisfied. Make sure that the new room has been checked by you or someone else, however, before it is assigned.). \n4 is the least effective response as the customer will still have a less than satisfactory room. Also, you don’t really know whether the customer wants a meal and wine, he may have already eaten or may not want to drink before an important business meeting. It is unlikely to ensure his satisfaction with your hotel). \n\n\n",
                "type": "most-least",
                "passage": "You are a trainee manager on a two year programme working for Superluxe Hotels, a national chain of 4 and 5 star hotels. \nThe programme ensures that trainees gain experience in all areas of hotel and hospitality \nmanagement through a rotational scheme of 4 month placements. You are currently undertaking your ‘Guest Services’ placement and you are based at the Alpston Grand, a five-star property and one of Superluxe’s flagship hotels. \nYou are working as second-in-command in the Grand Hotel Guest Services team; you report \ndirectly to the Guest Relations Manager. The primary job of the Guest Services team is to ensure that customers of the hotel receive an efficient and friendly welcome and departure, while ensuring the reception and front of house departments operate in an organised manner. The team must ensure a professional, friendly and courteous service is provided to all guests and that all complaints the hotel receives are handled properly. The Guest Services staff must also implement Superluxe occupancy policy which is to try to maximise occupancy on a daily basis.\n"
        },
        {
                "question": "It is 8pm on a Thursday evening in February. Fifty percent of the hotel’s 300 rooms are currently occupied and a customer without a previous reservation has just arrived at the reception desk. The customer has enquired about the price of a standard double room. You have informed her that the room rate is £120 per night, including breakfast. The customer then asks whether you can let her have the room and breakfast for £80. \nReview the following responses A to D and indicate which one you believe to be the response to the situation you would be ‘most likely to make’ and the response to the situation which you would be ‘least likely to make’. \n",
                "options": [
                        "Give her information on the town’s inexpensive B&B accommodation and how to find it. ",
                        "Say that you can offer her the room at £100 for the night and breakfast. ",
                        "Say that the room rate is £120 and there are no discounts available.",
                        "Say that if she returns at 9pm you will probably be able to give her a discount on the standard room rate then. "
                ],
                "correctAnswer": {
                        "most": 1,
                        "least": 2
                },
                "explanation": "2 is the most effective response as she was unlikely to have been expecting her first price to be accepted and was probably looking for you to split the difference between your first price and hers. In this way you have increased the hotel occupancy and ensured extra income to cover the fixed running costs which would be incurred whether or not that guest ended up staying.\n3 is the least effective response as the Superluxe policy is to maximise occupancy and half of the rooms are currently empty in the hotel. It is 8pm and therefore you are unlikely to fill the remaining 150 rooms, you may as well offer the customer some kind of deal to entice her to stay. The fixed costs of running the hotel remain the same whether it is empty or full.",
                "type": "most-least",
                "passage": "You are a trainee manager on a two year programme working for Superluxe Hotels, a national chain of 4 and 5 star hotels. \nThe programme ensures that trainees gain experience in all areas of hotel and hospitality \nmanagement through a rotational scheme of 4 month placements. You are currently undertaking your ‘Guest Services’ placement and you are based at the Alpston Grand, a five-star property and one of Superluxe’s flagship hotels. \nYou are working as second-in-command in the Grand Hotel Guest Services team; you report \ndirectly to the Guest Relations Manager. The primary job of the Guest Services team is to ensure that customers of the hotel receive an efficient and friendly welcome and departure, while ensuring the reception and front of house departments operate in an organised manner. The team must ensure a professional, friendly and courteous service is provided to all guests and that all complaints the hotel receives are handled properly. The Guest Services staff must also implement Superluxe occupancy policy which is to try to maximise occupancy on a daily basis. \n"
        },
        {
                "question": "The hotel is hosting a large banquet tomorrow night on behalf of a corporate client. The guest list was due to be 150 people, however, just now, you have received a call from the client contact and they have informed you that they had underestimated the numbers and that they need to increase the guestlist to 200 people. It is 10am. \nReview the following responses A to D and indicate which one you believe to be the response to the situation you would be ‘most likely to make’ and the response to the situation which you would be ‘least likely to make’. \n",
                "options": [
                        "Tell the client what the increased cost will be for the extra 50 guests based on the amount quoted per person for the original 150. ",
                        "Thank the client for informing you and say you will call back to confirm the booking once you have spoken to the Catering team. ",
                        "Thank the client for letting you know about the increase in numbers and then inform the Catering team that there will be 50 extra guests. ",
                        "Tell the client that the hotel will do everything it can to accommodate the extra numbers and you hope to be able to call them back and confirm the booking shortly. "
                ],
                "correctAnswer": {
                        "most": 3,
                        "least": 0
                },
                "explanation": "4 is the most effective response as you are making it clear to the client that the extra numbers are not confirmed yet but that you are going to do all you can to make the booking work. You can then check with the Catering team and perhaps offer help with getting in temporary staff etc before you call the client back to confirm.\n1 is the least effective response as, although the client will need to be informed of the new price, the first priority is to ensure that the hotel has the capacity to be able to cope with the extra guests and to still maintain an excellent quality service.",
                "type": "most-least",
                "passage": "You are a trainee manager on a two year programme working for Superluxe Hotels, a national chain of 4 and 5 star hotels. \nThe programme ensures that trainees gain experience in all areas of hotel and hospitality \nmanagement through a rotational scheme of 4 month placements. You are currently undertaking your ‘Guest Services’ placement and you are based at the Alpston Grand, a five-star property and one of Superluxe’s flagship hotels. \nYou are working as second-in-command in the Grand Hotel Guest Services team; you report \ndirectly to the Guest Relations Manager. The primary job of the Guest Services team is to ensure that customers of the hotel receive an efficient and friendly welcome and departure, while ensuring the reception and front of house departments operate in an organised manner. The team must ensure a professional, friendly and courteous service is provided to all guests and that all complaints the hotel receives are handled properly. The Guest Services staff must also implement Superluxe occupancy policy which is to try to maximise occupancy on a daily basis. \n"
        },
        {
                "question": "It is Saturday morning and you have just been informed that a large group booking is going to be transferred from the Saldringham Regent Hotel (also part of the Superluxe chain) to your hotel, as the Regent is overbooked. The group requires 110 rooms and the main conference suite to be made available from 6pm this evening. You have room availability tonight but not all of the rooms have been prepared as you weren’t expecting a high occupancy level. In order for all the rooms to be prepared the morning shift housekeeping staff will need to work an additional 2 hours each for which they will be paid overtime. Their shift normally finishes at 2pm. \nReview the following responses A to D and indicate which one you believe to be the response to the situation you would be ‘most likely to make’ and the response to the situation which you would be ‘least likely to make’. \n",
                "options": [
                        "Call the housekeeping staff together as soon as is convenient and then explain the situation to them saying that the group booking is great for the Alpston Grand as occupancy has been low recently and that they will be helping to keep the hotel running successfully. ",
                        "Ask the Senior Housekeeper to let the staff know that they will be required to work an extra 2 hours today. ",
                        "Call the housekeeping staff together and say you are sorry they will be needed for the extra two hours but hopefully the overtime pay will come in handy. ",
                        "Talk to the housekeeping staff and say that unfortunately they will have to work an extra 2 hours and you are very sorry. "
                ],
                "correctAnswer": {
                        "most": 0,
                        "least": 1
                },
                "explanation": "1 is the most effective response as you are explaining the benefits of the extra work and telling the staff how their efforts are contributing to the business.\n2 is the least effective response as you should communicate this to the staff yourself and ensure that the benefits and reasons are explained properly.",
                "type": "most-least",
                "passage": "You are a trainee manager on a two year programme working for Superluxe Hotels, a national chain of 4 and 5 star hotels. \nThe programme ensures that trainees gain experience in all areas of hotel and hospitality \nmanagement through a rotational scheme of 4 month placements. You are currently undertaking your ‘Guest Services’ placement and you are based at the Alpston Grand, a five-star property and one of Superluxe’s flagship hotels. \nYou are working as second-in-command in the Grand Hotel Guest Services team; you report \ndirectly to the Guest Relations Manager. The primary job of the Guest Services team is to ensure that customers of the hotel receive an efficient and friendly welcome and departure, while ensuring the reception and front of house departments operate in an organised manner. The team must ensure a professional, friendly and courteous service is provided to all guests and that all complaints the hotel receives are handled properly. The Guest Services staff must also implement Superluxe occupancy policy which is to try to maximise occupancy on a daily basis. \n"
        },
        {
                "question": "You are visiting The Pop-in Shop convenience store on Bentley Road, Saldringham this \nmorning. You have a friendly relationship with the proprietor, Ellen Gurty. Ellen has a regular order for a large number of your stationery lines such as pens, pencils, notepads, paper, wall tack and clear tape. However Ellen is grumbling today as trade hasn’t been brilliant for her of late and one of your rival suppliers, MoreThanPens Direct, has approached her with a great introductory deal on stationery. They are a specialist office goods supplier and are usually more expensive than Handy Goods, although the quality of their products is also slightly \nsuperior. The deal that MoreThanPens have offered Ellen is a bargain, and she has told you today that she has been sorely tempted. \nYou are authorised to give a 15% one-off discount to customers who say they might switch suppliers. You aren’t sure how serious Ellen is about swapping as you know she enjoys your visits and the MoreThanPens representative will not hang around for a cup of tea like you do as his patch is much larger. \nReview the following responses A to D and indicate whether you believe the response to be 1 – The most effective response, 2 – The second most effective response, 3 – The third most effective response or 4 – The least effective response . You may assign each rating only once. \n",
                "options": [
                        " Say to Ellen that you can understand that she is tempted by the offer from MoreThanPens and empathise with her recent poor sales. Talk to her about the likelihood that when the introductory offer runs out the prices could go higher than Handy Goods. Say you’d really like to talk to her this morning about what Handy Goods can do to keep her as a customer. ",
                        "Ignore Ellen’s grumblings and have a nice cup of tea and a chat with her about her grandchildren; that always seems to cheer her up. ",
                        "Have a chat with Ellen and ask her what her sales problems have been caused by. Say you can help her out with a 10% discount on this order if that will be helpful. ",
                        "Offer her a 15% discount on her latest order from Handy Goods. This will undercut MoreThanPens quite neatly. "
                ],
                "correctAnswer": [
                        1,
                        3,
                        4,
                        2
                ],
                "explanation": "A: The most effective response. You are communicating fully to Ellen how important she is as a customer and giving her the key piece of information about the prices being ‘introductory’ only for the rival supplier. Also, you are not giving away the 15% discount without any need but giving yourself an opportunity to use it if necessary when talking to Ellen about her relationship with Handy Goods.\n\nB: The least effective response. You are ignoring the possibility that Ellen is serious about changing suppliers and you are not communicating with her about the issue to let her know that you really value her custom.\n\nC: The second most effective response. You are giving a chance for Ellen to talk and listening to her answer about recent sales may give you some useful information. However, you need to ensure that she is fully aware of the difference between Handy Goods and MoreThanPens in the long-run.\n\nD: The third most effective response. You aren’t giving Ellen the information that would be useful for her to make a decision about the relative expensiveness of MoreThanPens in the long-run. It may not be necessary to offer the discount at all once she has that information to consider. Also you could do more to engage in conversation with Ellen, which is clearly one of the things she values about her relationship with Handy Goods.",
                "type": "ranking",
                "passage": "You are a Field Sales Representative for Handy Goods Ltd. Your company supplies independent corner shops and convenience stores with non-food ‘home essential’ products such as sewing thread, scissors, paperclips, nail clippers, bootlaces, drawing pins, liquid paper etc. Your brand prides itself on providing all the items that the stores’ customers might find it handy to be able to pick up along with their milk, bread and newspapers rather than having to make a special trip to the town centre shops. You have a range of 200 products and each is priced to allow your customers to be competitive with the High Street retailers. You are able to give discounts for bulk purchases. Your sales area is Saldringham City, its suburbs and outlying villages. You have 93 shops on your patch and you are tasked with visiting each one at least once each month. You spend an average of 20 to 30 minutes in a shop when you visit your customers.\n"
        },
        {
                "question": "It is a Monday morning in May. You have five shop visits booked in today all for shops in the central area of Saldringham City. You were then planning on returning to the office for the later part of the afternoon in order to catch up on a backlog of paperwork. Your manager has just called you to say that your colleague Wendy is off sick today. Wendy had three appointments today in Alpston which is a town about 40 minutes’ drive from Saldringham. Your manager is calling to ask whether you can cover any of the appointments as you are the closest sales rep to Wendy’s patch. \nReview the following responses A to D and indicate whether you believe the response to be 1 – The most effective response, 2 – The second most effective response, 3 – The third most effective response or 4 – The least effective response . You may assign each rating only once. \n",
                "options": [
                        "Apologise to your manager and explain that you would love to help but that you have a full schedule today and therefore you are unable to do so. Your paperwork needs to take precedence here otherwise you risk falling behind.",
                        "Say that you are busy today but may be able to take one of the visits on Wendy’s behalf, if other colleagues could cover the other two.",
                        "Agree to take all three appointments. You can attend all of your 5 visits this morning  and there will still be time to drive to Alpston and visit the three customers there. ",
                        "Agree to take all three appointments and call two of your customers to see if you can re-schedule their visits for tomorrow. "
                ],
                "correctAnswer": [
                        3,
                        4,
                        2,
                        1
                ],
                "explanation": "A: The least effective response. You are not considering the performance of the sales team as a whole only your own tasks and outputs. You are also ignoring the company / brand and how it will be affected by the missed visits. Perhaps you could negotiate with your manager to complete the paperwork a little late this time, given the exceptional circumstances.\n\nB: The third most effective response. You are the closest sales rep and therefore it would probably be more efficient for the team as a whole if you could do all three appointments once you are in Alpston.\n\nC: The most effective response. You are contributing to the whole team performance, not just worrying about your own patch. You would need to check the scheduling of both your and Wendy’s visits of course, in order that you could make sure that the timetable was achievable and realistic for you.) Bear in mind that it is your manager who has asked you to cover Wendy's appointments, so you should have a good reason to decline. \n\n\nD: The second most effective response. You are seeing the ‘whole team’ picture and working to maintain a good performance over both patches. However there should be a way of fitting all the appointments, yours and Wendy’s, into the day without having to cancel any visits.\n",
                "type": "ranking",
                "passage": "You are a Field Sales Representative for Handy Goods Ltd. Your company supplies independent corner shops and convenience stores with non-food ‘home essential’ products such as sewing thread, scissors, paperclips, nail clippers, bootlaces, drawing pins, liquid paper etc. Your brand prides itself on providing all the items that the stores’ customers might find it handy to be able to pick up along with their milk, bread and newspapers rather than having to make a special trip to the town centre shops. You have a range of 200 products and each is priced to allow your customers to be competitive with the High Street retailers. You are able to give discounts for bulk purchases. Your sales area is Saldringham City, its suburbs and outlying villages. You have 93 shops on your patch and you are tasked with visiting each one at least once each month. You spend an average of 20 to 30 minutes in a shop when you visit your customers."
        },
        {
                "question": "You have just come out of a Monday morning team briefing. You have been informed that \nsales of children’s pocket toys and games have been very slow recently and that Handy Goods wish to ensure that sales targets for this product line are achieved, and preferably exceeded. \nAs such, each Field Sales Representative will be reviewed fortnightly on their toys & games sales. The representative who achieves the highest sales for this line each fortnight will receive a cash bonus and the representative with the lowest sales will be shadowed by the Field Sales trainer and given intensive coaching. This representative will also be required to complete a detailed report on all of their visits over that fortnight in order for selling opportunities to be analysed by the trainer to inform the coaching sessions. You are keen to be the highest selling representative but at the very least you are desperate to avoid being the lowest selling as the extra work sounds quite onerous and dispiriting. \nReview the following responses A to D and indicate whether you believe the response to be \n1 – The most effective response, 2 – The second most effective response, 3 – The third most effective response or 4 – The least effective response . You may assign each rating only once. \n",
                "options": [
                        "Decide that for every visit you do from now on you won't leave the shop until the customer agrees to at least look at the product line of toys & games.",
                        "Switch your appointments around this month so that over the next two weeks you will visit all the shops that are located near schools and nurseries. You will have the best chance of selling the pocket toys & games product line to these shops.",
                        "Ensure that your product samples for toys & games are bang up-to-date and that you  know all about each product and its target market. Aim to talk about toys & games at every sales visit and ask detailed questions to the customers about their requirements in this area. ",
                        "Ask all your customers about their sales of toys & games and talk in more detail to the ones who have a good turnover of these types of products about Handy Goods’ range. "
                ],
                "correctAnswer": [
                        3,
                        4,
                        2,
                        1
                ],
                "explanation": "A: The least effective response. You run the risk of badgering your customers, alienating them and affecting your supplier relationship in the long-term.\n\nB: The third most effective response. This may help you achieve a good level of sales in the first half of the month but it does nothing for your sales figures going forward.\n\nC: The most effective response. By knowing your products really well, presenting them well and understanding your customers’ needs you should be able to match something that you have to offer to their requirements. Also, simply making sure that you mention the product line each time should have an impact on your hit rate.\n\nD: The second most effective response. You are targeting the most likely customers, however you may be missing a trick if you don’t talk to all your customers about the product line. Also, you need to ensure that your product knowledge is solid and up-to-date.\n",
                "type": "ranking",
                "passage": "You are a Field Sales Representative for Handy Goods Ltd. Your company supplies independent corner shops and convenience stores with non-food ‘home essential’ products such as sewing thread, scissors, paperclips, nail clippers, bootlaces, drawing pins, liquid paper etc. Your brand prides itself on providing all the items that the stores’ customers might find it handy to be able to pick up along with their milk, bread and newspapers rather than having to make a special trip to the town centre shops. You have a range of 200 products and each is priced to allow your customers to be competitive with the High Street retailers. You are able to give discounts for bulk purchases. Your sales area is Saldringham City, its suburbs and outlying villages. You have 93 shops on your patch and you are tasked with visiting each one at least once each month. You spend an average of 20 to 30 minutes in a shop when you visit your customers."
        },
        {
                "question": "You are conducting a regular visit with one of your customers in Saldringham’s outlying villages. The Village Store in Brancombe Brook is the only shop in the area and incorporates the Post Office, a delicatessen, an upmarket off-licence and general store. \nRuth Hardlow is the manager of the shop which is owned and run as a cooperative by the villagers. Shortly after you arrived today Miss Hardlow brought up an issue with regard to the quality of some of the products that Handy Goods supply to the store. Miss Hardlow said that in recent weeks she has had 7 customers return products from the Handy Goods range, according to her, due to “shoddy quality”. Miss Hardlow particularly mentioned the sewing items, needles, thread and scissors as well as some items of stationery. She reminded you that customers here rely on the shop and need to know that the things they buy here are as good quality as those in town. Miss Hardlow appears upset and angry about the issue and the last thing she has said to you is that she is seriously considering looking at other suppliers for her non-food items. \nReview the following responses A to D and indicate whether you believe the response to be \n1 – The most effective response, 2 – The second most effective response, 3 – The third most effective response or 4 – The least effective response . You may assign each rating only once. ",
                "options": [
                        "Take a note of the products which have been found faulty by The Village Store customers and say that you will report the matter to your Product Line team when you get back to the office.",
                        "Give Miss Hardlow some ‘free gift’ items in her next order as an apology. Say that you are sure these products were just from a ‘bad batch’ that slipped past quality control and you are sure it won’t happen again. After all her customers are bound to come back to the Store even if there are problems, as it’s the only shop in the village. ",
                        "Apologise to Miss Hardlow. Ask to see the returned products and examine them. Say that you will investigate what has happened and contact her next week to update her. ",
                        "Apologise to Miss Hardlow and offer a full refund for the goods. "
                ],
                "correctAnswer": [
                        3,
                        4,
                        1,
                        2
                ],
                "explanation": "A: The third most effective response. You are doing nothing to immediately deal with the problem for Miss Hardlow and giving her no timescales as to when the issues might be resolved.\n\nB: The least effective response. You have no idea why these products are poor quality or at least why the customers in Brancombe Brook believe them to be. You are doing nothing to investigate or solve Miss Hardlow’s problem in the longer-term. Being complacent about quality will not help Miss Hardlow keep her customers in the long-run as they appear to be relatively affluent looking at what else the Store sells.\n\nC: The most effective response. You are taking the problem seriously’. If the products do turn out to be faulty then Handy Goods may need to communicate this to all its customers and offer Miss Hardlow a refund; if not, then you can return to Miss Hardlow and explain this politely.\n\nD: The second most effective response. She will be happy that she is not ‘out-of-pocket’ for the items, however you should also investigate the reasons for the products being returned in case the problem is real and systematic. If this is the case, other customers will need to be informed.\n",
                "type": "ranking",
                "passage": "You are a Field Sales Representative for Handy Goods Ltd. Your company supplies independent corner shops and convenience stores with non-food ‘home essential’ products such as sewing thread, scissors, paperclips, nail clippers, bootlaces, drawing pins, liquid paper etc. Your brand prides itself on providing all the items that the stores’ customers might find it handy to be able to pick up along with their milk, bread and newspapers rather than having to make a special trip to the town centre shops. You have a range of 200 products and each is priced to allow your customers to be competitive with the High Street retailers. You are able to give discounts for bulk purchases. Your sales area is Saldringham City, its suburbs and outlying villages. You have 93 shops on your patch and you are tasked with visiting each one at least once each month. You spend an average of 20 to 30 minutes in a shop when you visit your customers."
        },
        {
                "question": "A customer has come through to you with a complaint about Greenwinds billing system. He \nis a new customer who has used the Greenwinds Dual Fuel electricity and gas product for a month. He says that he wasn’t told by the doorstep sales person when he signed up that the electricity would not be split into off-peak and peak rate units. With his previous supplier he had been used to maximising his energy use at night in order to benefit from the cheaper rate electricity. He was under the impression that he would be able to continue to do this with Greenwinds and now he is very upset as he has realised, upon receiving his first bill, that this is not the case. \nReview the following responses A to D and indicate which you believe to be the ‘most effective’ response to the situation and which the ‘least effective’. \n",
                "options": [
                        "Apologise for the confusion but state that the Greenwinds charging policy is clearly written on the joining contract and on the website. ",
                        "Apologise for the confusion and ask the customer for more detail about the sales  conversation, including the salesperson’s name or description. Say that you will ask your manager to investigate the way that the contract was sold and to look at whether any miscommunication had happened on the doorstep. Say you will get back to the customer on a daily basis to keep him updated of progress. ",
                        "Apologise for the confusion and offer the customer a goodwill waiver of one month’s standing charge. ",
                        "Apologise for the confusion and say that you are sorry to hear that he is feeling upset  and hope that Greenwinds excellent service and eco-friendly product will make up for the initial misunderstanding in the long-run. "
                ],
                "correctAnswer": {
                        "most": 1,
                        "least": 0
                },
                "explanation": "2 is the most effective response as the customer will feel that he is being taken seriously and have a chance to calm down. You will remain in contact with him regularly and can use this opportunity to talk about Greenwinds and keep him apprised of the investigation. Finding out what happened on the doorstep can help to decide whether the salesperson did or did not mention the ‘one-rate’ policy. And if not, were they deliberately misleading the customer or did they make a genuine mistake in failing to mention the policy. Once this is established the salesperson can receive training or coaching to improve their performance or the company can take other measures as appropriate. Also the customer can be dealt with fairly, either by allowing him to cancel his contract or by awarding him a fair gesture of apology such as a discounted rate, etc\n\n1 is the least effective response as you are doing nothing to assist the customer in any way and simply leaving him to remain angry at Greenwinds and possibly publicise his complaints another way i.e. internet or broadcast media.",
                "type": "most-least",
                "passage": "You are a customer advisor at the UK contact centre for Greenwinds Energy. Greenwinds is a renewable-source electricity and gas supplier to European domestic and business customers. Your role is to answer inbound telephone calls and emails from customers in the UK, answering questions and queries about Greenwinds products and services and dealing with customer complaints and issues. You work in a team of 15 and you report into a Customer Service Team Leader. \nGreenwinds has recently introduced a ‘one-rate’ policy for all its energy packages. \nCustomers will be charged the same rate per unit of electricity or gas regardless of their method of payment or when their peak usage of energy is. This has many advantages including, greater clarity of charging, no encouragement for use of electrical appliances at night, which can be unsafe, and no discrimination against people using pre-pay meters, pre pay cards or monthly cheque payment, all of whom are traditionally the less prosperous customers.\n"
        },
        {
                "question": "You have recently noticed that your fellow team member, Sandy, is raising his voice quite frequently at the customers and has terminated a few calls early when customers have been expressing dissatisfaction in a rude or discourteous way. Another colleague told you in confidence that Sandy has got problems at home, his wife recently lost her job, they are experiencing financial strain and it is taking its toll on their relationship. Sandy is worried that his wife is depressed and he is finding it hard to concentrate on work properly. You sit next to Sandy in the contact centre and you have noticed his behaviour becoming more erratic over the last few weeks. \nReview the following responses A to D and indicate which you believe to be the ‘most effective’ response to the situation and which the ‘least effective’. \n",
                "options": [
                        " Do nothing. It is not your responsibility to intervene with Sandy, it is up to the Customer Service Team Leader to respond if his work is suffering. You feel that Sandy would be upset and offended if you ‘poked your nose in’ with his personal problems.",
                        "Speak to Sandy and say that you want him to know that you are always available for a chat if he ever needs someone to talk to. Ask him if there is anything that you can do to help and support him at work as you have noticed him dealing with customers differently recently, not in his usual friendly, calm manner.",
                        "Say to Sandy that you have noticed that his personal life is affecting his work and say that he had better watch out that the Team Leader doesn’t give him a formal warning about the way he is dealing with customers.",
                        "Tell your Team Leader that you are worried about Sandy and that you know that he has some problems at home. Say to the Team Leader that you are happy to take on some of Sandy’s workload whilst he is feeling stressed and under pressure."
                ],
                "correctAnswer": {
                        "most": 1,
                        "least": 2
                },
                "explanation": "2 is the most effective response as you are showing Sandy that you are aware that he may be feeling stressed and upset at the moment. On the other hand, you are leaving it up to him to tell you what he feels comfortable with and offering practical support as well.\n3 is the the least effective response as you are increasing the pressure on Sandy in a rather hostile way and you are not offering anything in the way of support or help.",
                "type": "most-least",
                "passage": "You are a customer advisor at the UK contact centre for Greenwinds Energy. Greenwinds is a renewable-source electricity and gas supplier to European domestic and business customers. Your role is to answer inbound telephone calls and emails from customers in the UK, answering questions and queries about Greenwinds products and services and dealing with customer complaints and issues. You work in a team of 15 and you report into a Customer Service Team Leader. \nGreenwinds has recently introduced a ‘one-rate’ policy for all its energy packages. \nCustomers will be charged the same rate per unit of electricity or gas regardless of their method of payment or when their peak usage of energy is. This has many advantages including, greater clarity of charging, no encouragement for use of electrical appliances at night, which can be unsafe, and no discrimination against people using pre-pay meters, pre pay cards or monthly cheque payment, all of whom are traditionally the less prosperous customers.\n"
        },
        {
                "question": "Today is Monday. You had a team meeting this morning in which your Team Leader mentioned that the Head Office was unhappy with current levels of customer satisfaction with the contact centre and that there has been a dip in service quality. She said that, therefore, she would be looking closely at the service quality report every week and is expecting an improvement. The way that the contact centre service quality is measured has recently been changed: a new customer satisfaction survey has been introduced which is emailed to customers. Mystery shoppers have also been employed to call at random and record the way that they are dealt with by contact centre staff. \n\nReview the following responses A to D and indicate which you believe to be the ‘most effective’ response to the situation and which the ‘least effective’. \n",
                "options": [
                        "Make an extra special effort to be warm, friendly and helpful to customers throughout the week. ",
                        "Look at Greenwinds intranet ‘service quality’ site which outlines the new measurement methods in detail. Analyse the customer satisfaction questions and the mystery shopper criteria and change your behaviour, if necessary, to ensure that you are fulfilling these requirements. ",
                        "Wait for a further briefing from your Team Leader. She usually sends a note round following the team meeting summarising what was said. You are hopeful that she will be more specific in this note as to what is required of you in order to improve the service quality ratings.",
                        "Ask for a quick chat with your Team Leader sometime today and find out from her what she feels will be the best way for you to contribute to the service quality targets. Make sure you are aware of the details of the new customer satisfaction measure and the Mystery Shopper criteria before you talk to her."
                ],
                "correctAnswer": {
                        "most": 3,
                        "least": 2
                },
                "explanation": "4 is the most effective response as your Team Leader should be able to understand and tailor the service quality requirements to your specific role. By talking it through with her you will be able to be very specific about if, or how, you need to change your behaviour with customers.\n3 is the least effective response as your Team Leader may simply repeat what she said at the meeting which was too vague to be able to help you decide if, or how, to change your behaviour.",
                "type": "most-least",
                "passage": "You are a customer advisor at the UK contact centre for Greenwinds Energy. Greenwinds is a renewable-source electricity and gas supplier to European domestic and business customers. Your role is to answer inbound telephone calls and emails from customers in the UK, answering questions and queries about Greenwinds products and services and dealing with customer complaints and issues. You work in a team of 15 and you report into a Customer Service Team Leader. \nGreenwinds has recently introduced a ‘one-rate’ policy for all its energy packages. \nCustomers will be charged the same rate per unit of electricity or gas regardless of their method of payment or when their peak usage of energy is. This has many advantages including, greater clarity of charging, no encouragement for use of electrical appliances at night, which can be unsafe, and no discrimination against people using pre-pay meters, pre-pay cards or monthly cheque payment, all of whom are traditionally the less prosperous customers.\n"
        },
        {
                "question": "You are working a 10am to 6pm shift today. You have just returned from your lunch break at 2pm and your colleague informs you that the IT system which allows access to customer accounts and billing information has crashed. IT support have said that they won’t be able to fix the system until 4.30pm. Your normal rate of calls is 7 or 8 queries an hour. Your Team Leader has sent an email to the whole team asking you to carry on answering customer calls and deal with them as best you can until the system is fixed. \nReview the following responses A to D and indicate which you believe to be the ‘most effective’ response to the situation and which the ‘least effective’",
                "options": [
                        "Calculate that you will probably receive about 20 calls over the next 2.5 hours and that some of these may be queries that you can deal with easily using the website or other resources. Resolve to take the details of the other customers and call them back between 4.30pm and 6pm. You may have to call some of them on the following day as 5pm onwards is peak evening call time and you will be busy with new calls. ",
                        "Go and see your Team Leader and ask her what she expects you to do with customers who need to respond to a billing or account query today, after all it’s her responsibility to provide some leadership in this stressful situation. It’s probably not realistic to call them all back after 4.30pm as that is the start of the peak evening call time and inbound calls will be going up to 9 or 10 calls an hour per advisor then. ",
                        "Suggest to your Team Leader that when the system is back up and running after 4.30pm that one customer advisor could be allocated to getting back to all the afternoon customers who’s queries were not resolved, whilst the other advisors deal with the new inbound calls.",
                        "Deal with the straightforward queries that come in but ask all other customers to call  back after 4.30pm. It will be too difficult to schedule outbound calls when the evening peak begins."
                ],
                "correctAnswer": {
                        "most": 0,
                        "least": 3
                },
                "explanation": "1 is the most effective response as you are taking responsibility for providing a good service despite the pressures of the situation. Also the fact that you will call these customers back yourself means that the second time you speak to them should be an efficient use of call time as you have already got the ‘gist’ of their query from their initial call.\n4 is the least effective response as, although the situation is difficult, you still have a responsibility to provide excellent service to customers.",
                "type": "most-least",
                "passage": "You are a customer advisor at the UK contact centre for Greenwinds Energy. Greenwinds is a renewable-source electricity and gas supplier to European domestic and business customers. Your role is to answer inbound telephone calls and emails from customers in the UK, answering questions and queries about Greenwinds products and services and dealing with customer complaints and issues. You work in a team of 15 and you report into a Customer Service Team Leader. \nGreenwinds has recently introduced a ‘one-rate’ policy for all its energy packages. \nCustomers will be charged the same rate per unit of electricity or gas regardless of their method of payment or when their peak usage of energy is. This has many advantages including, greater clarity of charging, no encouragement for use of electrical appliances at night, which can be unsafe, and no discrimination against people using pre-pay meters, pre-pay cards or monthly cheque payment, all of whom are traditionally the less prosperous customers.\n"
        },
        {
                "question": "A customer has called the contact centre and is interested in changing her mobile phone tariff  and handset as her annual contract is due for renewal next month. She has come through to you and has said that she is finding the information on the website very confusing and isn’t sure which would be the best tariff for her and how to get the latest ‘smartphone’ as inexpensively as possible. She says that her phone, text and data usage is liable to stay pretty much the same in the coming year as it was in the past 12 months. She is confident in her choice of handset. \nReview the following responses A to E and indicate whether you believe the response to be 1 Most Effective, 2 Effective, 3 Slightly Effective, 4 Least Effective, or 5 Counterproductive. You may assign each rating only once.\n",
                "options": [
                        "Tell her that you will take a detailed look at her account and then email her the details of the three best price packages for her. State that you will call her in an hour or two (or some other time convenient to her), once she has had a chance to read the email and talk her through the information and answer any questions. ",
                        "Talk through the information about all the various available tariffs with her and the related prices of the handset she wants. ",
                        "State that the best place to find all the information is the website and that if she puts the name of the handset that she requires into the search engine then she will find some useful information. ",
                        " Ask her to wait whilst you take a thorough look at her account and then talk her through the details of the two or three best price packages for her. Once you have established her preferred package through the conversation, then email her the details of this including the cost of the handset.",
                        "Tell her that you will take a detailed look at her account and then email her the details of the two or three best price packages for her. "
                ],
                "correctAnswer": [
                        1,
                        4,
                        5,
                        2,
                        3
                ],
                "explanation": "A: The Very Effective response. This tailors the information and reduces the amount of information that the customer has to trawl through and also gives her the chance to receive the information in two ways – orally and in a written format – and also gives her a chance to have any questions answered.\n\nB: The Ineffective response. This does little to reduce the amount of information that the customer has to trawl through and only gives her the information in only one format. She has already said that she finds the website unhelpful and therefore when she gets off the phone she will not have anything in writing to which to refer.\n\nC: The Counterproductive response. She has already said that she finds the website confusing and you haven’t established whether she has tried this ‘search’ approach already anyway.\n\nD: The Effective response. This tailors the information and reduces the amount of information that the customer has to trawl through and it also gives her some of the information in written format; however it is less effective than the best response because she is being required to make decisions based on oral information only\n\nE: The Slightly Effective response. This tailors the information and reduces the amount of information that the customer has to trawl through, however it only allows her the information in one format. It also makes it more difficult for her to ask questions as she will have to call back and possibly talk to someone else rather than to you.\n",
                "type": "ranking",
                "passage": "You are an advisor working in a customer contact centre for a large telecommunications company called JoinedUp. The company provides mobile phone services and handsets, broadband internet and landline services to domestic and business customers in the UK and Europe."
        },
        {
                "question": "You have just finished a customer call and turned to your colleague, Alexis, who looked troubled and concerned. You asked what was wrong and she said that she had just had to put a customer through to the team leader because she wasn’t able to explain a new mobile phone text & data tariff which had just been released by JoinedUp today. The team leader briefed the team about the new tariff this morning and said that it was important to promote it as it had been designed to compete directly with an offer made by a competitor in TV ads last week. \nReview the following responses A to E and indicate whether you believe the response to be 1 Most Effective, 2 Effective, 3 Slightly Effective, 4 Least Effective or 5 Counterproductive. You may assign each rating only once.",
                "options": [
                        "Offer to talk Alexis through the new tariff and answer any questions she may have.",
                        "As time is tight you write down a few key points about the tariff and leave it on her workstation for her to have as a reminder if another customer enquiries. ",
                        "Say that the tariff is very straightforward to understand really and that she’ll soon get the hang of it. ",
                        "Suggest that Alexis asks the team leader for another briefing on the tariff and that it’s nothing to be worried about as you have sometimes found new products difficult to fathom at first. ",
                        "Tell her that you’ll email her the briefing document that your team leader handed out this morning to remind her of the details of the tariff."
                ],
                "correctAnswer": [
                        1,
                        2,
                        4,
                        5,
                        3
                ],
                "explanation": "A: The Very Effective response. You are being directly supportive and helpful to your colleague and improving the team’s chances of performing effectively.\n\nB: The Slightly Effective response. It may help her but it would be better if you gave her time to ask questions so you could directly address the points with which she was struggling.\n\nC: The Counterproductive response. This will undermine her confidence as she is clearly not finding the tariff straightforward and she may also now be reluctant to ask anyone else for help for fear of looking stupid.\n\nD: The Effective response. You are being emotionally supportive if not immediately offering practical help yourself but making a reasonable suggestion to Alexis.\n\nE: The Ineffective response. It may be that Alexis has lost the original document but not very likely. It is more likely that she can’t understand it and in that sense you are not being particularly helpful.",
                "type": "ranking",
                "passage": "You are an advisor working in a customer contact centre for a large telecommunications company called JoinedUp. The company provides mobile phone services and handsets, broadband internet and landline services to domestic and business customers in the UK and Europe"
        },
        {
                "question": "Your team leader called you over this morning and said that she thought you would like to know that, in the last quarter results, you were one of the JoinedUp top 20 UK customer advisors for call quality and efficiency. This means that, compared to other customer advisors, you had managed your calls effectively in terms of customer satisfaction and that you had answered the right number of calls per hour and your calls had mostly been of the target length suggested by JoinedUp. \nThis result suggests that in this current quarter you have a chance of achieving a longstanding personal goal and earning a substantial bonus payment into the bargain. The top 10 customer advisors each quarter receive a bonus payment worth 15% of their salary. There are 2 months of this current quarter remaining and you are keen to do your best to get into that ‘top 10’ list. \nReview the following responses A to E and indicate whether you believe the response to be 1 Most Effective, 2 Effective, 3 Slightly Effective, 4 Least Effective or 5 Counterproductive. You may assign each rating only once.",
                "options": [
                        "Find out from your team leader who the advisors in the Top 10 were last quarter. Email them and ask if any can spare fifteen minutes for a chat and see if you can glean any hints and tips for improving your performance even further.",
                        "Tell your colleagues that you are in the Top 20 advisors and say that you will bring cakes and doughnuts tomorrow to celebrate. ",
                        "Cancel the three days annual leave that you had booked in for next week as you want to make sure you are one of the top performers. ",
                        "Keep working as you have been. After all “if it ain’t broke...” as the saying goes. ",
                        "Ask your team leader for feedback and advice on how to achieve Top 10 status. "
                ],
                "correctAnswer": [
                        1,
                        5,
                        4,
                        2,
                        3
                ],
                "explanation": "A: The Very Effective response. Getting advice “from the horse’s mouth”, as it were, should give you a range of ideas for tweaking and improving your performance.\n\nB: The Ineffective response. This is a nice gesture towards your co-workers but will have no effect on your performance this quarter.\n\nC: The Counterproductive response. The number of days you work is not one of the measures and, by cancelling a break, you are risking increasing your fatigue and stress levels which will not help your performance.\n\nD: The Slightly Effective response. There is some logic to this view which is that you have already made it into the Top 20 last quarter and so with a bit of luck you may achieve the Top 10 without changing your approach to work. However, the danger is that your current approach is just not enough to equal the ‘best’ customer advisors’ performance\n\nE: The Effective response. Your team leader should have a good idea of your current performance and may have some useful tips on how to improve even further to put you in that very top section of the list.",
                "type": "ranking",
                "passage": "You are an advisor working in a customer contact centre for a large telecommunications company called JoinedUp. The company provides mobile phone services and handsets, broadband internet and landline services to domestic and business customers in the UK and Europe."
        },
        {
                "question": "It is 10am on a Tuesday. JoinedUp launched the ‘Yphone Xtra’ mobile handset today which is the new, sought-after handset of the moment. Customers can acquire the Yphone at a very low cost when they sign up to a 12 or 24 month contract for mobile phone services with JoinedUp. There is an additional offer that the first 1000 customers who sign-up for a relevant JoinedUp mobile contract qualify for a free Yphone. The handset and the offer were made available from 9am today and since then the call centre has been experiencing a very high level of calls. \nYour team leader has told you that you will be required to work an extra 4 hours from 4pm until 8pm, at the end of your 8 hour shift today but you’ll be able to take the time-off-in-lieu sometime next week. Everyone in the team will also have shortened lunch breaks today, again with the time being recouped next week. You haven’t said anything to your team leader but you have a report to write for your BTEC in Contact Centre Leadership tonight; it is due in by midday tomorrow and you are working tomorrow morning.\nReview the following responses A to E and indicate whether you believe the response to be 1 Most Effective, 2 Effective, 3 Slightly Effective, 4 Least Effective or 5 Counterproductive. You may assign each rating only once.",
                "options": [
                        "Contact your BTEC tutor and ask for an extension on the report deadline, if at all possible, explain that you are in a uniquely demanding work situation. If the extension isn’t granted see if you can reduce your shift from 12 to 10 hours by explaining your predicament to your team leader. ",
                        "Work very quickly through the calls that you receive in the hope that the call numbers will dwindle later and your team leader will let you go earlier.",
                        " Refuse to work the extra time tonight although you will take a shorter lunch break. Tell your team leader that you have a prior engagement this evening that you cannot break. ",
                        "Call a colleague who is on leave today and see if they can cover for your extra 4 hours.",
                        "Ask your team leader if there is any lee-way in this arrangement as you have an urgent report to write tonight and it is a work-related assignment. Say that you will take a minimal break and work 10 hours without distraction. "
                ],
                "correctAnswer": [
                        1,
                        5,
                        4,
                        2,
                        3
                ],
                "explanation": "A: The Very Effective response. You are tackling the situation from two angles and hopefully, either your tutor or your team leader will be able to ‘cut you some slack’ in this case.\n\nB: The Ineffective response. You are jeopardising customer service and satisfaction. Also you are very unlikely to be able to individually influence overall call handling rates.\n\nC: The Counterproductive response. This is a rather ‘panicky’ response to the change in timetable for the day. You should consider other options, such as contacting your BTEC tutor and asking for an extension on the deadline before appearing uncooperative at work.\n\nD: The Slightly Effective response. You may be lucky and find someone willing to come in for you. Although you will have to square it with the team leader who may not be pleased as she would probably have to pay overtime rather than give time off in lieu as the colleague would be giving up their booked leave.\n\nE: The Effective response. You are being co-operative and responsive to the work demands although there may be other ways you could address the situation, like asking for an extension on your work.",
                "type": "ranking",
                "passage": "You are an advisor working in a customer contact centre for a large telecommunications company called JoinedUp. The company provides mobile phone services and handsets, broadband internet and landline services to domestic and business customers in the UK and Europe."
        }
],
    timeLimit: 1200 // 20 minutes in seconds
};

// Initialize the test
const testCore = new TestCore(testConfig);
testCore.start();